# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Publish

on:
  release:
    types: [published]

jobs:
  publish-to-npm:
    if: github.repository_owner == 'chartjs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: node scripts/publish-to-npm.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
